import type { TenderSource } from "@/lib/types";

export type TenderSourceSeed = Pick<
  TenderSource,
  | "source_name"
  | "organization_type"
  | "region"
  | "prefecture"
  | "base_url"
  | "tender_list_url"
  | "open_counter_url"
  | "result_url"
  | "target_types"
  | "source_format"
  | "crawler_type"
  | "crawler_difficulty"
  | "crawl_priority"
  | "crawl_frequency"
  | "is_active"
  | "robots_note"
  | "terms_note"
  | "admin_note"
  | "crawl_ready"
>;

const defaultNote = "公式公開ページ。robots.txt と利用規約を本番クロール前に確認する。";

function seed(input: Omit<TenderSourceSeed, "target_types" | "source_format" | "crawler_difficulty" | "crawl_frequency" | "robots_note" | "terms_note" | "crawl_ready"> & Partial<TenderSourceSeed>): TenderSourceSeed {
  return {
    target_types: input.target_types ?? ["goods", "services", "open_counter", "qualification_required"],
    source_format: input.source_format ?? "html",
    crawler_difficulty: input.crawler_difficulty ?? "medium",
    crawl_frequency: input.crawl_frequency ?? "weekly",
    robots_note: input.robots_note ?? "未確認",
    terms_note: input.terms_note ?? "未確認",
    crawl_ready: input.crawl_ready ?? false,
    ...input
  };
}

export const TENDER_SOURCE_SEEDS: TenderSourceSeed[] = [
  seed({ source_name: "調達ポータル", organization_type: "national_government", region: "全国", prefecture: null, base_url: "https://www.p-portal.go.jp/", tender_list_url: "https://www.p-portal.go.jp/", crawler_type: "p_portal", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "調達情報検索", organization_type: "national_government", region: "全国", prefecture: null, base_url: "https://www.p-portal.go.jp/", tender_list_url: "https://www.p-portal.go.jp/pps-web-biz/UAA01/OAA0101", source_format: "search_form", crawler_type: "p_portal", crawl_priority: "A", is_active: true, admin_note: "国物件の中核。500件上限時は日付・地域・機関で分割取得する。" }),
  seed({ source_name: "政府電子調達 GEPS 旧ポータル", organization_type: "national_government", region: "全国", prefecture: null, base_url: "https://www.geps.go.jp/", tender_list_url: "https://www.geps.go.jp/", source_format: "mixed", crawler_type: "e_procurement_system", crawler_difficulty: "high", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "官公需情報ポータルサイト", organization_type: "national_government", region: "全国", prefecture: null, base_url: "https://www.kkj.go.jp/s/", tender_list_url: "https://www.kkj.go.jp/s/", source_format: "search_form", crawler_type: "kkj_portal", crawler_difficulty: "high", crawl_priority: "A", is_active: true, admin_note: "地方自治体横断の補完元。完全収録は保証しない前提。" }),
  seed({ source_name: "JETRO 政府公共調達データベース", organization_type: "independent_agency", region: "全国", prefecture: null, base_url: "https://www.jetro.go.jp/", tender_list_url: "https://www.jetro.go.jp/gov_procurement/", crawler_type: "generic_html", crawl_priority: "B", is_active: true, admin_note: defaultNote }),

  seed({ source_name: "空き家 公告・公示・公募", organization_type: "defense_ministry", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/", tender_list_url: "https://www.mod.go.jp/j/budget/chotatsu/index.html", crawler_type: "defense_mod", crawl_priority: "A", is_active: true, admin_note: "空き家本省だけでなく各調達機関を直接巡回する。" }),
  seed({ source_name: "空き家 調達機関リンク集", organization_type: "defense_ministry", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/", tender_list_url: "https://www.mod.go.jp/j/budget/chotatsu/ichiran.html", crawler_type: "defense_mod", crawl_priority: "A", is_active: true, admin_note: "調達機関の追加登録元。" }),
  seed({ source_name: "空き家 内部部局", organization_type: "defense_ministry", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/", tender_list_url: "https://www.mod.go.jp/j/budget/chotatsu/naikyoku/index.html", crawler_type: "defense_mod", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "統合幕僚監部 調達情報", organization_type: "defense_ministry", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/js/", tender_list_url: "https://www.mod.go.jp/js/supply/index.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "陸上古家 調達情報総合", organization_type: "ground_self_defense_force", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/", tender_list_url: "https://www.mod.go.jp/gsdf/procurement_information/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "北部方面会計隊", organization_type: "ground_self_defense_force", region: "北海道", prefecture: "北海道", base_url: "https://www.mod.go.jp/gsdf/nae/fin/", tender_list_url: "https://www.mod.go.jp/gsdf/nae/fin/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "北部方面会計隊 0円物件", organization_type: "ground_self_defense_force", region: "北海道", prefecture: "北海道", base_url: "https://www.mod.go.jp/gsdf/nae/fin/", tender_list_url: "https://www.mod.go.jp/gsdf/nae/fin/nafin/R7open.html", open_counter_url: "https://www.mod.go.jp/gsdf/nae/fin/nafin/R7open.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東北方面会計隊", organization_type: "ground_self_defense_force", region: "東北", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/neae/", tender_list_url: "https://www.mod.go.jp/gsdf/neae/neahq/koukoku/finindex.htm", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東部方面会計隊", organization_type: "ground_self_defense_force", region: "関東", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/eae/", tender_list_url: "https://www.mod.go.jp/gsdf/eae/kaikei/eafin/nyusatsu_ekimu.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "中部方面会計隊", organization_type: "ground_self_defense_force", region: "中部", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/mae/mafin/", tender_list_url: "https://www.mod.go.jp/gsdf/mae/mafin/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "西部方面会計隊", organization_type: "ground_self_defense_force", region: "九州", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/wae/info/nyusatu/wa-fin/", tender_list_url: "https://www.mod.go.jp/gsdf/wae/info/nyusatu/wa-fin/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "西部方面会計隊 0円物件", organization_type: "ground_self_defense_force", region: "九州", prefecture: null, base_url: "https://www.mod.go.jp/gsdf/wae/info/nyusatu/wa-fin/open/", tender_list_url: "https://www.mod.go.jp/gsdf/wae/info/nyusatu/wa-fin/open/", open_counter_url: "https://www.mod.go.jp/gsdf/wae/info/nyusatu/wa-fin/open/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "北海道補給処 物件情報", organization_type: "ground_self_defense_force", region: "北海道", prefecture: "北海道", base_url: "https://www.mod.go.jp/gsdf/nae/nadep/", tender_list_url: "https://www.mod.go.jp/gsdf/nae/nadep/nyuusatujouhou/nyuusatujouhou.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "海上古家 調達情報", organization_type: "maritime_self_defense_force", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/msdf/", tender_list_url: "https://www.mod.go.jp/msdf/supply/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "航空古家 調達情報", organization_type: "air_self_defense_force", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/asdf/", tender_list_url: "https://www.mod.go.jp/asdf/choutatsu/index.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "防衛装備庁 調達・公募情報", organization_type: "defense_equipment_agency", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/atla/", tender_list_url: "https://www.mod.go.jp/atla/choutatsu.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "情報本部 調達情報", organization_type: "defense_ministry", region: "全国", prefecture: null, base_url: "https://www.mod.go.jp/dih/", tender_list_url: "https://www.mod.go.jp/dih/supply/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "防衛研究所 調達情報", organization_type: "defense_ministry", region: "関東", prefecture: "東京都", base_url: "https://www.nids.mod.go.jp/", tender_list_url: "https://www.nids.mod.go.jp/procurement/index.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "防衛医科大学校 調達情報", organization_type: "defense_ministry", region: "関東", prefecture: "埼玉県", base_url: "https://www.ndmc.ac.jp/", tender_list_url: "https://www.ndmc.ac.jp/info/information/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),

  seed({ source_name: "北海道防衛局", organization_type: "defense_bureau", region: "北海道", prefecture: "北海道", base_url: "https://www.mod.go.jp/rdb/hokkaido/", tender_list_url: "https://www.mod.go.jp/rdb/hokkaido/keiyaku/index.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東北防衛局", organization_type: "defense_bureau", region: "東北", prefecture: "宮城県", base_url: "https://www.mod.go.jp/rdb/tohoku/", tender_list_url: "https://www.mod.go.jp/rdb/tohoku/index.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "北関東防衛局", organization_type: "defense_bureau", region: "関東", prefecture: "埼玉県", base_url: "https://www.mod.go.jp/rdb/n-kanto/", tender_list_url: "https://www.mod.go.jp/rdb/n-kanto/nyusatsu-keiyaku/nyusatsu-keiyaku.html", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "南関東防衛局", organization_type: "defense_bureau", region: "関東", prefecture: "神奈川県", base_url: "https://www.mod.go.jp/rdb/s-kanto/", tender_list_url: "https://www.mod.go.jp/rdb/s-kanto/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "近畿中部防衛局", organization_type: "defense_bureau", region: "近畿", prefecture: "大阪府", base_url: "https://www.mod.go.jp/rdb/kinchu/", tender_list_url: "https://www.mod.go.jp/rdb/kinchu/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東海防衛支局", organization_type: "defense_bureau", region: "中部", prefecture: "愛知県", base_url: "https://www.mod.go.jp/rdb/tokai/", tender_list_url: "https://www.mod.go.jp/rdb/tokai/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "中国四国防衛局", organization_type: "defense_bureau", region: "中国", prefecture: "広島県", base_url: "https://www.mod.go.jp/rdb/chushi/", tender_list_url: "https://www.mod.go.jp/rdb/chushi/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "九州防衛局", organization_type: "defense_bureau", region: "九州", prefecture: "福岡県", base_url: "https://www.mod.go.jp/rdb/kyushu/", tender_list_url: "https://www.mod.go.jp/rdb/kyushu/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "沖縄防衛局", organization_type: "defense_bureau", region: "沖縄", prefecture: "沖縄県", base_url: "https://www.mod.go.jp/rdb/okinawa/", tender_list_url: "https://www.mod.go.jp/rdb/okinawa/contract/", crawler_type: "defense_unit", crawl_priority: "A", is_active: true, admin_note: defaultNote }),

  seed({ source_name: "内閣府 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.cao.go.jp/", tender_list_url: "https://www.cao.go.jp/chotatsu/", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "内閣府 契約公表", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.cao.go.jp/", result_url: "https://www.cao.go.jp/chotatsu/kohyo/kohyo.html", tender_list_url: "https://www.cao.go.jp/chotatsu/kohyo/kohyo.html", target_types: ["results"], crawler_type: "ministry_page", crawl_priority: "C", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "法務省 資格審査・調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.moj.go.jp/", tender_list_url: "https://www.moj.go.jp/chotatsu_index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "外務省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mofa.go.jp/", tender_list_url: "https://www.mofa.go.jp/mofaj/annai/shocho/chotatsu/chotatsu_index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "財務省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mof.go.jp/", tender_list_url: "https://www.mof.go.jp/application-contact/procurement/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "財務省 物品・役務", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mof.go.jp/", tender_list_url: "https://www.mof.go.jp/application-contact/procurement/buppinn/index.htm", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "文部科学省 調達総合案内", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mext.go.jp/", tender_list_url: "https://www.mext.go.jp/b_menu/choutatsu/index.htm", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "文部科学省 調達情報ウェブサイト", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://pf.mext.go.jp/", tender_list_url: "https://pf.mext.go.jp/gpo3/kanpo/gpoindex.asp", source_format: "search_form", crawler_type: "e_procurement_system", crawler_difficulty: "high", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "厚生労働省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mhlw.go.jp/", tender_list_url: "https://www.mhlw.go.jp/shinsei_boshu/choutatsujouhou/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "厚生労働省 調達情報一覧", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mhlw.go.jp/", tender_list_url: "https://www.mhlw.go.jp/stf/shinsei_boshu/choutatsujouhou/chotatu/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "農林水産省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.maff.go.jp/", tender_list_url: "https://www.maff.go.jp/j/supply/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "農林水産省 0円物件・物件", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.maff.go.jp/", tender_list_url: "https://www.maff.go.jp/j/supply/nyusatu/index.html", open_counter_url: "https://www.maff.go.jp/j/supply/nyusatu/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "経済産業省 調達・予算執行", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.meti.go.jp/", tender_list_url: "https://www.meti.go.jp/information/publicoffer/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "経済産業省 物件情報一覧", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.meti.go.jp/", tender_list_url: "https://www.meti.go.jp/information_2/publicoffer/R_00_bid_news_list.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "国土交通省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mlit.go.jp/", tender_list_url: "https://www.mlit.go.jp/appli/file000001.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "国土交通省 航空局系 調達・契約", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.mlit.go.jp/", tender_list_url: "https://www.mlit.go.jp/koku/15_bf_000277.html", crawler_type: "ministry_page", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "環境省 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.env.go.jp/", tender_list_url: "https://www.env.go.jp/kanbo/chotatsu/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "環境省 役務", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.env.go.jp/", tender_list_url: "https://www.env.go.jp/kanbo/chotatsu/index_ekimu.html", crawler_type: "ministry_page", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "環境省 委託", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.env.go.jp/", tender_list_url: "https://www.env.go.jp/kanbo/chotatsu/index_itaku.html", crawler_type: "ministry_page", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "デジタル庁 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.digital.go.jp/", tender_list_url: "https://www.digital.go.jp/procurement", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "警察庁 調達情報", organization_type: "ministry", region: "関東", prefecture: "東京都", base_url: "https://www.npa.go.jp/", tender_list_url: "https://www.npa.go.jp/news/procurement/npa/index.html", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "中国経済産業局 調達情報", organization_type: "local_branch", region: "中国", prefecture: "広島県", base_url: "https://www.chugoku.meti.go.jp/", tender_list_url: "https://www.chugoku.meti.go.jp/nyusatu.html", crawler_type: "ministry_page", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "九州地方環境事務所 調達情報", organization_type: "local_branch", region: "九州", prefecture: "熊本県", base_url: "https://kyushu.env.go.jp/", tender_list_url: "https://kyushu.env.go.jp/procure/", crawler_type: "ministry_page", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "関東財務局 調達情報", organization_type: "local_branch", region: "関東", prefecture: "埼玉県", base_url: "https://lfb.mof.go.jp/kantou/", tender_list_url: "https://lfb.mof.go.jp/kantou/tyoutatsu/index.htm", crawler_type: "ministry_page", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "JICA 調達情報", organization_type: "independent_agency", region: "全国", prefecture: null, base_url: "https://www.jica.go.jp/", tender_list_url: "https://www.jica.go.jp/about/announce/", crawler_type: "generic_html", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "UR都市再生機構 物件・契約情報", organization_type: "independent_agency", region: "全国", prefecture: null, base_url: "https://www.ur-net.go.jp/", tender_list_url: "https://www.ur-net.go.jp/order/", crawler_type: "generic_html", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "国立病院機構 調達情報", organization_type: "hospital_organization", region: "全国", prefecture: null, base_url: "https://nho.hosp.go.jp/", tender_list_url: "https://nho.hosp.go.jp/bid/news_bid_2025_00001.html", crawler_type: "generic_html", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東京大学 調達情報", organization_type: "national_university", region: "関東", prefecture: "東京都", base_url: "https://www.u-tokyo.ac.jp/", tender_list_url: "https://www.u-tokyo.ac.jp/ja/about/procurement-contracts/chotatsu-index.html", crawler_type: "generic_html", crawl_priority: "B", is_active: true, admin_note: defaultNote }),

  seed({ source_name: "北海道 物件・調達情報", organization_type: "prefecture", region: "北海道", prefecture: "北海道", base_url: "https://www.pref.hokkaido.lg.jp/", tender_list_url: "https://www.pref.hokkaido.lg.jp/category/d003/c006/", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "北海道 物件結果", organization_type: "prefecture", region: "北海道", prefecture: "北海道", base_url: "https://www.pref.hokkaido.lg.jp/", result_url: "https://www.pref.hokkaido.lg.jp/category/d003/c006/s013/", tender_list_url: "https://www.pref.hokkaido.lg.jp/category/d003/c006/s013/", target_types: ["results"], crawler_type: "local_government", crawl_priority: "C", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "青森県 水道企業局 0円物件", organization_type: "prefecture", region: "東北", prefecture: "青森県", base_url: "https://www.pref.aomori.lg.jp/", tender_list_url: "https://www.pref.aomori.lg.jp/soshiki/suido/suidokigyo/open_counter.html", open_counter_url: "https://www.pref.aomori.lg.jp/soshiki/suido/suidokigyo/open_counter.html", crawler_type: "local_government", crawl_priority: "C", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "岩手県 物件・コンペ・公募情報", organization_type: "prefecture", region: "東北", prefecture: "岩手県", base_url: "https://www.pref.iwate.jp/", tender_list_url: "https://www.pref.iwate.jp/kensei/nyuusatsu/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "宮城県 物品等電子調達", organization_type: "prefecture", region: "東北", prefecture: "宮城県", base_url: "https://www.pref.miyagi.jp/", tender_list_url: "https://www.pref.miyagi.jp/soshiki/keiyaku/kst.html", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "山形県 物品・役務調達システム", organization_type: "prefecture", region: "東北", prefecture: "山形県", base_url: "https://www.pref.yamagata.jp/", tender_list_url: "https://www.pref.yamagata.jp/480001/buppinndensi.html", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "茨城県 物件・調達・公売", organization_type: "prefecture", region: "関東", prefecture: "茨城県", base_url: "https://www.pref.ibaraki.jp/", tender_list_url: "https://www.pref.ibaraki.jp/shiru/nyusatsu-chotatsu/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "栃木県 電子調達システム", organization_type: "prefecture", region: "関東", prefecture: "栃木県", base_url: "https://www.pref.tochigi.lg.jp/", tender_list_url: "https://www.pref.tochigi.lg.jp/i02/buppinnekimunodennsika.html", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "群馬県 物件・公売・公募", organization_type: "prefecture", region: "関東", prefecture: "群馬県", base_url: "https://www.pref.gunma.jp/", tender_list_url: "https://www.pref.gunma.jp/site/nyuusatsu/", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "群馬県 物品等・0円物件", organization_type: "prefecture", region: "関東", prefecture: "群馬県", base_url: "https://www.pref.gunma.jp/", tender_list_url: "https://www.pref.gunma.jp/site/nyuusatsu/list135-771.html", open_counter_url: "https://www.pref.gunma.jp/site/nyuusatsu/list135-771.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "埼玉県 物品・委託等", organization_type: "prefecture", region: "関東", prefecture: "埼玉県", base_url: "https://www.pref.saitama.lg.jp/", tender_list_url: "https://www.pref.saitama.lg.jp/a0212/kense/tetsuzuki/nyusatsu/buppin/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "埼玉県 電子物件", organization_type: "prefecture", region: "関東", prefecture: "埼玉県", base_url: "https://www.pref.saitama.lg.jp/", tender_list_url: "https://www.pref.saitama.lg.jp/a0212/densinyusatsu/index.html", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "千葉県 0円物件", organization_type: "prefecture", region: "関東", prefecture: "千葉県", base_url: "https://www.pref.chiba.lg.jp/", tender_list_url: "https://www.pref.chiba.lg.jp/kanzai/open-counter/index.html", open_counter_url: "https://www.pref.chiba.lg.jp/kanzai/open-counter/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東京都 契約・物件情報", organization_type: "prefecture", region: "関東", prefecture: "東京都", base_url: "https://www.metro.tokyo.lg.jp/", tender_list_url: "https://www.metro.tokyo.lg.jp/tosei/zaise/keiyaku", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "東京都 電子調達", organization_type: "prefecture", region: "関東", prefecture: "東京都", base_url: "https://www.e-procurement.metro.tokyo.lg.jp/", tender_list_url: "https://www.e-procurement.metro.tokyo.lg.jp/", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "神奈川県 物品等の購入", organization_type: "prefecture", region: "関東", prefecture: "神奈川県", base_url: "https://www.pref.kanagawa.jp/", tender_list_url: "https://www.pref.kanagawa.jp/menu/5/22/124/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "神奈川県 物件結果", organization_type: "prefecture", region: "関東", prefecture: "神奈川県", base_url: "https://www.pref.kanagawa.jp/", result_url: "https://www.pref.kanagawa.jp/docs/g7r/cnt/f3430/p10822.html", tender_list_url: "https://www.pref.kanagawa.jp/docs/g7r/cnt/f3430/p10822.html", target_types: ["results"], crawler_type: "local_government", crawl_priority: "C", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "富山県 物件情報", organization_type: "prefecture", region: "中部", prefecture: "富山県", base_url: "https://www.pref.toyama.jp/", tender_list_url: "https://www.pref.toyama.jp/sangyou/nyuusatsu/jouhou/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "富山県 物品・役務", organization_type: "prefecture", region: "中部", prefecture: "富山県", base_url: "https://www.pref.toyama.jp/", tender_list_url: "https://www.pref.toyama.jp/sangyou/nyuusatsu/jouhou/buppin/joho.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "熊本県 物件情報", organization_type: "prefecture", region: "九州", prefecture: "熊本県", base_url: "https://www.pref.kumamoto.jp/", tender_list_url: "https://www.pref.kumamoto.jp/life/sub/5/", crawler_type: "local_government", crawl_priority: "A", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "熊本県 電子物件 公開システム", organization_type: "prefecture", region: "九州", prefecture: "熊本県", base_url: "https://ebid-portal.kumamoto-idc.pref.kumamoto.jp/", tender_list_url: "https://ebid-portal.kumamoto-idc.pref.kumamoto.jp/koukaisystem.html", crawler_type: "e_procurement_system", crawler_difficulty: "high", crawl_priority: "A", is_active: false, admin_note: defaultNote }),

  seed({ source_name: "札幌市 公開見積合せ", organization_type: "designated_city", region: "北海道", prefecture: "北海道", base_url: "https://www.city.sapporo.jp/", tender_list_url: "https://www.city.sapporo.jp/shobo/shokai/koukai/koukai.html", open_counter_url: "https://www.city.sapporo.jp/shobo/shokai/koukai/koukai.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "さいたま市 物件・契約", organization_type: "designated_city", region: "関東", prefecture: "埼玉県", base_url: "https://www.city.saitama.lg.jp/", tender_list_url: "https://www.city.saitama.lg.jp/005/001/017/index.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "横浜市 物件・契約情報", organization_type: "designated_city", region: "関東", prefecture: "神奈川県", base_url: "https://keiyaku.city.yokohama.lg.jp/", tender_list_url: "https://keiyaku.city.yokohama.lg.jp/epco/keiyaku/info.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "横浜市 物品・委託・公募型見積", organization_type: "designated_city", region: "関東", prefecture: "神奈川県", base_url: "https://keiyaku.city.yokohama.lg.jp/", tender_list_url: "https://keiyaku.city.yokohama.lg.jp/epco/keiyaku/hacchujoho_buppin.html", open_counter_url: "https://keiyaku.city.yokohama.lg.jp/epco/keiyaku/hacchujoho_buppin.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "横浜市 物件契約結果", organization_type: "designated_city", region: "関東", prefecture: "神奈川県", base_url: "https://keiyaku.city.yokohama.lg.jp/", result_url: "https://keiyaku.city.yokohama.lg.jp/epco/servlet/p?job=NyusatsuKeiyakuKekkaBuppinSearch", tender_list_url: "https://keiyaku.city.yokohama.lg.jp/epco/servlet/p?job=NyusatsuKeiyakuKekkaBuppinSearch", target_types: ["results"], crawler_type: "local_government", crawl_priority: "C", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "名古屋市 電子調達システム", organization_type: "designated_city", region: "中部", prefecture: "愛知県", base_url: "https://www.chotatsu.city.nagoya.jp/", tender_list_url: "https://www.chotatsu.city.nagoya.jp/", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "名古屋市 物件情報", organization_type: "designated_city", region: "中部", prefecture: "愛知県", base_url: "https://www.chotatsu.city.nagoya.jp/", tender_list_url: "https://www.chotatsu.city.nagoya.jp/ejpkg/EjPPIj", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "大阪市 物件契約情報", organization_type: "designated_city", region: "近畿", prefecture: "大阪府", base_url: "https://www.city.osaka.lg.jp/", tender_list_url: "https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "大阪市 電子調達", organization_type: "designated_city", region: "近畿", prefecture: "大阪府", base_url: "https://www.keiyaku.city.osaka.lg.jp/", tender_list_url: "https://www.keiyaku.city.osaka.lg.jp/", crawler_type: "e_procurement_system", crawl_priority: "B", is_active: false, admin_note: defaultNote }),
  seed({ source_name: "福岡市 物品定例見積", organization_type: "designated_city", region: "九州", prefecture: "福岡県", base_url: "https://www.city.fukuoka.lg.jp/", tender_list_url: "https://www.city.fukuoka.lg.jp/zaisei/keiyaku-info/keiyaku_hp/contract02.html", open_counter_url: "https://www.city.fukuoka.lg.jp/zaisei/keiyaku-info/keiyaku_hp/contract02.html", crawler_type: "local_government", crawl_priority: "B", is_active: true, admin_note: defaultNote }),
  seed({ source_name: "熊本市 物件・契約", organization_type: "designated_city", region: "九州", prefecture: "熊本県", base_url: "https://www.city.kumamoto.jp/", tender_list_url: "https://www.city.kumamoto.jp/list04195.html", crawler_type: "local_government", crawl_priority: "A", is_active: true, admin_note: defaultNote })
];
