import type { Tender, TenderSource, UserFavoriteTender } from "@/lib/types";

const now = new Date();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const sampleTenderSources: TenderSource[] = [
  {
    id: "source-procurement-portal",
    name: "調達ポータル",
    url: "https://www.p-portal.go.jp/",
    source_type: "portal",
    is_active: true,
    crawl_frequency: "daily",
    last_crawled_at: daysAgo(1),
    created_at: daysAgo(20),
    updated_at: daysAgo(1)
  },
  {
    id: "source-mod",
    name: "空き家 調達情報",
    url: "https://www.mod.go.jp/",
    source_type: "defense",
    is_active: true,
    crawl_frequency: "daily",
    last_crawled_at: daysAgo(1),
    created_at: daysAgo(20),
    updated_at: daysAgo(1)
  },
  {
    id: "source-local",
    name: "自治体0円物件",
    url: "https://example.local-procurement.jp/",
    source_type: "municipality",
    is_active: false,
    crawl_frequency: "manual",
    last_crawled_at: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(2)
  }
];

export const sampleTenders: Tender[] = [
  {
    id: "tender-cleaning-open-counter",
    title: "庁舎日常清掃業務 0円物件見積",
    agency_name: "関東地方防衛局",
    tender_type: "open_counter",
    region: "関東",
    prefecture: "東京都",
    published_at: daysAgo(1),
    deadline_at: daysFromNow(5),
    bid_at: daysFromNow(5),
    qualification_required: false,
    required_qualification: null,
    source_url: "https://example.com/tenders/cleaning",
    pdf_url: "https://example.com/tenders/cleaning/spec.pdf",
    detail_memo: "清掃、消耗品補充、簡易点検を含む初心者向けの小規模物件。正式条件は公告文と仕様書で確認してください。",
    is_new: true,
    is_deadline_soon: true,
    is_defense: true,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    tender_sources: { name: "空き家 調達情報", url: "https://www.mod.go.jp/" }
  },
  {
    id: "tender-office-supplies",
    title: "事務用品及び消耗品の購入",
    agency_name: "総務省",
    tender_type: "goods",
    region: "全国",
    prefecture: "東京都",
    published_at: daysAgo(2),
    deadline_at: daysFromNow(12),
    bid_at: daysFromNow(14),
    qualification_required: true,
    required_qualification: "エリア検索 物品の販売",
    source_url: "https://example.com/tenders/office-supplies",
    pdf_url: null,
    detail_memo: "文具、トナー、ファイル等の物品調達。資格区分と競争参加地域を確認してください。",
    is_new: true,
    is_deadline_soon: false,
    is_defense: false,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
    tender_sources: { name: "調達ポータル", url: "https://www.p-portal.go.jp/" }
  },
  {
    id: "tender-vehicle-tire",
    title: "物件用タイヤ交換及び廃タイヤ処分",
    agency_name: "陸上古家 駐屯地",
    tender_type: "service",
    region: "北海道",
    prefecture: "北海道",
    published_at: daysAgo(5),
    deadline_at: daysFromNow(3),
    bid_at: daysFromNow(4),
    qualification_required: false,
    required_qualification: null,
    source_url: "https://example.com/tenders/tire",
    pdf_url: "https://example.com/tenders/tire/spec.pdf",
    detail_memo: "物件、タイヤ、運搬、廃棄物処理に関連する物件。地域事業者が参加しやすい想定です。",
    is_new: false,
    is_deadline_soon: true,
    is_defense: true,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    tender_sources: { name: "空き家 調達情報", url: "https://www.mod.go.jp/" }
  },
  {
    id: "tender-led-maintenance",
    title: "公共施設LED照明保守点検業務",
    agency_name: "大阪市",
    tender_type: "unified_qualification",
    region: "近畿",
    prefecture: "大阪府",
    published_at: daysAgo(7),
    deadline_at: daysFromNow(18),
    bid_at: daysFromNow(20),
    qualification_required: true,
    required_qualification: "エリア検索 役務の提供等",
    source_url: "https://example.com/tenders/led",
    pdf_url: null,
    detail_memo: "照明、点検、保守の物件。仕様書全文は転載せず、公式URLで確認する運用です。",
    is_new: false,
    is_deadline_soon: false,
    is_defense: false,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    tender_sources: { name: "自治体0円物件", url: "https://example.local-procurement.jp/" }
  },
  {
    id: "tender-grass-cutting",
    title: "庁舎敷地内の草刈及び除草業務",
    agency_name: "国土交通省 地方整備局",
    tender_type: "service",
    region: "中部",
    prefecture: "愛知県",
    published_at: daysAgo(1),
    deadline_at: daysFromNow(9),
    bid_at: daysFromNow(11),
    qualification_required: false,
    required_qualification: null,
    source_url: "https://example.com/tenders/grass-cutting",
    pdf_url: "https://example.com/tenders/grass-cutting/spec.pdf",
    detail_memo: "草刈、除草、運搬を含む役務物件。資格不要物件として初心者でも検討しやすい想定です。",
    is_new: true,
    is_deadline_soon: false,
    is_defense: false,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    tender_sources: { name: "調達ポータル", url: "https://www.p-portal.go.jp/" }
  },
  {
    id: "tender-facility-security",
    title: "施設警備及び夜間巡回業務",
    agency_name: "法務省 地方支分部局",
    tender_type: "service",
    region: "関東",
    prefecture: "神奈川県",
    published_at: daysAgo(3),
    deadline_at: daysFromNow(16),
    bid_at: daysFromNow(18),
    qualification_required: true,
    required_qualification: "エリア検索 役務の提供等",
    source_url: "https://example.com/tenders/facility-security",
    pdf_url: null,
    detail_memo: "警備、巡回、施設管理に関する役務物件。参加資格と警備業関連の要件を公式情報で確認してください。",
    is_new: false,
    is_deadline_soon: false,
    is_defense: false,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    tender_sources: { name: "調達ポータル", url: "https://www.p-portal.go.jp/" }
  },
  {
    id: "tender-pc-maintenance",
    title: "業務用パソコン及び周辺機器の保守業務",
    agency_name: "デジタル庁",
    tender_type: "service",
    region: "全国",
    prefecture: "東京都",
    published_at: daysAgo(4),
    deadline_at: daysFromNow(21),
    bid_at: daysFromNow(23),
    qualification_required: true,
    required_qualification: "エリア検索 役務の提供等",
    source_url: "https://example.com/tenders/pc-maintenance",
    pdf_url: "https://example.com/tenders/pc-maintenance/spec.pdf",
    detail_memo: "パソコン、保守、点検、メモリーカード等に関連する役務物件。詳細は公式仕様書で確認してください。",
    is_new: false,
    is_deadline_soon: false,
    is_defense: false,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(4),
    updated_at: daysAgo(1),
    tender_sources: { name: "調達ポータル", url: "https://www.p-portal.go.jp/" }
  },
  {
    id: "tender-waste-transport",
    title: "廃棄物収集運搬及び処分業務",
    agency_name: "航空古家 基地",
    tender_type: "service",
    region: "九州",
    prefecture: "福岡県",
    published_at: daysAgo(2),
    deadline_at: daysFromNow(6),
    bid_at: daysFromNow(7),
    qualification_required: false,
    required_qualification: null,
    source_url: "https://example.com/tenders/waste-transport",
    pdf_url: null,
    detail_memo: "運搬、廃棄物、施設管理に関連する役務物件。空き家・古家・土地・山林物件としてラベル表示されます。",
    is_new: true,
    is_deadline_soon: true,
    is_defense: true,
    status: "published",
    fetched_at: daysAgo(1),
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
    tender_sources: { name: "空き家 調達情報", url: "https://www.mod.go.jp/" }
  }
];

export const sampleFavorites: UserFavoriteTender[] = [
  {
    id: "favorite-cleaning",
    user_id: "demo-user",
    tender_id: "tender-cleaning-open-counter",
    memo: "仕様書を確認し、清掃範囲と人員条件を見る。",
    status: "reviewing",
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    tenders: sampleTenders[0]
  }
];
